### ISSUE TITLE
BOT ERROR 

### ISSUE THREAD

**Issue by Falghere** [BeepIsla/csgo-commend-bot#175]
I'm trying to use the bot in my vps (ubuntu) and I'm having this error can you tell me what it is?

(windows is working normally)

```
/bot/commendbot/index.js:117
                } catch {
                        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

```

**Comment by BeepIsla** [comment]
Update NodeJS. Read the README, it clearly says you need NodeJS v12.

**Comment by Falghere** [comment]
@BeepIsla 
I just upgraded the node to latest version and am still having the same error

Does the bot not work on ubuntu VPS?

**Comment by BeepIsla** [comment]
The latest NodeJS version is v13, which also doesn't work. You have to use v12. This bot works on any OS.

[Read the instructions on how to install NodeJS on Ubuntu/Debian.](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions)
