### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kutayexe** [BeepIsla/csgo-commend-bot#180]
csgo-commend-bot-master\databaseManager.js:10
(async () => {
       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Config**

[config.json.txt](https://github.com/BeepIsla/csgo-commend-bot/files/3965236/config.json.txt)

**Version**
- NodeJS: `v6.9.0` 
- Script version: `2.2.4`

**Comment by BeepIsla** [comment]
Read the README, it l
early says use NodeJS v12 with a download link.
