### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by Velortex** [BeepIsla/csgo-commend-bot#186]
Is this a error of my proxy configuration or a error of the software im using squid as proxyserver

**Additional information**
root@server:/home/nodejs/csgo-commend-bot# node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Loading proxies...
 Got 1 proxy
 Opening database...
 There are a total of 363 operational accounts
 Getting an available server
 Logging into target account
 Chunking 5 accounts into groups of 15...
 Getting an available server
 Selected available server 85568392922664436
 Logging in on chunk 1/1
 [addiewilkins1980] Logging into Steam
 [adelefilippi1999] Logging into Steam
 [adelegerritsen8] Logging into Steam
 [adelinenatali2013] Logging into Steam
 [agnesvisani50] Logging into Steam
(node:19069) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_PROTOCOL]: Protocol "proxy1.velortex.cc:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:119:11)
    at Object.request (http.js:42:10)
    at new TCPConnection (/home/nodejs/csgo-commend-bot/node_modules/steam-user/components/connection_protocols/tcp.js:45:18)
    at SteamUser._doConnection (/home/nodejs/csgo-commend-bot/node_modules/steam-user/components/logon.js:238:23)
    at process.nextTick (/home/nodejs/csgo-commend-bot/node_modules/steam-user/components/logon.js:218:8)
(node:19069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19069) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_PROTOCOL]: Protocol "proxy1.velortex.cc:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:119:11)
    at Object.request (http.js:42:10)
    at Agent.agent.createConnection (/home/nodejs/csgo-commend-bot/node_modules/@doctormckay/stdlib/components/http/proxyagent.js:42:56)
    at Agent.createSocket (_http_agent.js:227:26)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:249:16)
    at request (https.js:289:10)
    at Object.get (https.js:293:15)
    at WebSocketConnection._pingCM (/home/nodejs/csgo-commend-bot/node_modules/steam-user/components/connection_protocols/websocket.js:207:8)
    at promises.push.Promise (/home/nodejs/csgo-commend-bot/node_modules/steam-user/components/connection_protocols/websocket.js:47:10)
    at new Promise (<anonymous>)
    at user._cmList.websocket_servers.forEach (/home/nodejs/csgo-commend-bot/node_modules/steam-user/components/connection_protocols/websocket.js:46:18)
    at Array.forEach (<anonymous>)
    at WebSocketConnection.g_BootstrapSemaphore.wait (/home/nodejs/csgo-commend-bot/node_modules/steam-user/components/connection_protocols/websocket.js:40:39)
    at AsyncQueue.Semaphore._next [as worker] (/home/nodejs/csgo-commend-bot/node_modules/@doctormckay/stdlib/components/concurrency/semaphore.js:41:2)
    at AsyncQueue._process (/home/nodejs/csgo-commend-bot/node_modules/@doctormckay/stdlib/components/data_structures/asyncqueue.js:83:7)
(node:19069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 83)

**Comment by BeepIsla** [comment]
Prefix your proxies with `http://`

**Comment by Velortex** [comment]
thx for fast respond
