### ISSUE TITLE
GCHello error

### ISSUE THREAD

**Issue by aciidiic** [BeepIsla/csgo-commend-bot#233]
Error: GC connection timeout - GCHello
    at Timeout._onTimeout (C:\Users\Jim\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\helpers\GameCoordinator.js:89:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) Promise {
  <rejected> Error: GC connection timeout - GCHello
      at Timeout._onTimeout (C:\Users\Jim\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\helpers\GameCoordinator.js:89:12)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
}

**Comment by BeepIsla** [comment]
Use the issue templates.

What is your config?

What are you trying to do?

When does this happen?

So many open questions.

**Comment by aciidiic** [comment]
https://gyazo.com/6ff1f707ad4281698b022305483e539f

https://gyazo.com/5b1842dad7edfb18c8cccdbb174cbb22

Attempting to commend and it happens after logging into fetcher accouunt. My appologies.

**Comment by BeepIsla** [comment]
Are you trying to commend the same account which is in "fetcher"?

**Comment by aciidiic** [comment]
Mmmmmmmmmmmmmmmmmmmm. May be the problem then.

**Comment by BeepIsla** [comment]
The `fetcher` account is completely independent. Just generate a random account and use it as a fetcher.

Also the account in `account` is only used if you use `LOGIN` method. You don't have to fill that in if you use `SERVER` method.

**Comment by aciidiic** [comment]
Ahh. Thank you. Got it working. Closing now. :)
