### ISSUE TITLE
Doesnt works for me

### ISSUE THREAD

**Issue by MrPupir** [BeepIsla/csgo-commend-bot#245]
**Error**
```
root@rgm-servers:~/csgo-commend-bot# node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 1420 operational accounts
 Getting an available server
 Logging into target account
{
  name: 'Error',
  message: 'GC connection timeout - GCHello',
  stack: 'Error: GC connection timeout - GCHello\n' +
    '    at Timeout._onTimeout (/root/csgo-commend-bot/helpers/GameCoordinator.js:89:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
```

**Config**
```
{
	"commend": {
		"friendly": 1000,
		"teaching": 1000,
		"leader": 1000
	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "**********",
		"password": "**********",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "https://steamcommunity.com/id/mrpupir_official",
	"serverID": "AUTO",
	"matchID": "AUTO",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "**********",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v12.10.0`
- Script version: `2.6.0`

**Additional information**
I have Ubuntu 16.04 x64

**Comment by BeepIsla** [comment]
You're using LOGIN method without providing an account in the `account` part of the config.

**Comment by MrPupir** [comment]
Thank you! Now it's working! For me, a foreigner, the word "fetcher" has misled.
