### ISSUE TITLE
commend 19/20  may stop working

### ISSUE THREAD

**Issue by crx9** [BeepIsla/csgo-commend-bot#279]
when commending to (19/20),process may be suspended .Even if i enter "enter" in cmd, it won't continue.(Low probability occurrence)

**Comment by BeepIsla** [comment]
Screenshot the output and show config when it happens the next time. Until then there is absolutely nothing I can do with this little bit of information.

**Comment by crx9** [comment]
> Screenshot the output and show config when it happens the next time. Until then there is absolutely nothing I can do with this little bit of information.

ok

**Comment by crx9** [comment]
[skyalsdn] Logged onto Steam - GC Time: 2020-3-1 23:04:33
 [skybaboy46] Successfully sent a commend with response code 1 - Remaining Commends: 2 (8/20)
 [skyblue0604] Authenticated to anonymous server with ticket 1359982273
 [skyjin210] Authenticated to anonymous server with ticket 2322713416
 [skyjyy00] Authenticated to anonymous server with ticket 1661919404
 [skydum12] Authenticated to anonymous server with ticket 3432844959
 [skyblue0604] Successfully sent a commend with response code 1 - Remaining Commends: 2 (9/20)
 [skyjin210] Successfully sent a commend with response code 1 - Remaining Commends: 2 (10/20)
 [skyalsdn] Authenticated to anonymous server with ticket 255540182
 [skyline520GTR] Logged onto Steam - GC Time: 2020-3-1 23:04:34
 [skyjyy00] Successfully sent a commend with response code 1 - Remaining Commends: 2 (11/20)
 [skydum12] Successfully sent a commend with response code 1 - Remaining Commends: 2 (12/20)
 [skyhsieh] Authenticated to anonymous server with ticket 4032645507
 [skyalsdn] Successfully sent a commend with response code 1 - Remaining Commends: 2 (13/20)
 [skyjustop] Logged onto Steam - GC Time: 2020-3-1 23:04:35
 [skyline520GTR] Authenticated to anonymous server with ticket 1209770275
 [skyhsieh] Successfully sent a commend with response code 1 - Remaining Commends: 2 (14/20)
 [skydf1300] Logged onto Steam - GC Time: 2020-3-1 23:04:35
 [skyab510] Logged onto Steam - GC Time: 2020-3-1 23:04:35
 [skyline520GTR] Successfully sent a commend with response code 1 - Remaining Commends: 2 (15/20)
 [skyjustop] Authenticated to anonymous server with ticket 2535347170
 [skydf1300] Authenticated to anonymous server with ticket 4141468019
 [skyjustop] Successfully sent a commend with response code 1 - Remaining Commends: 2 (16/20)
 [skyab510] Authenticated to anonymous server with ticket 2188058852
 [skydf1300] Successfully sent a commend with response code 1 - Remaining Commends: 2 (17/20)
 [skyab510] Successfully sent a commend with response code 1 - Remaining Commends: 2 (18/20)
 [sky9380] Logged onto Steam - GC Time: 2020-3-1 23:04:38
 [sky9380] Authenticated to anonymous server with ticket 3686352031
 [sky9380] Successfully sent a commend with response code 1 - Remaining Commends: 2 (19/20)



{
	"commend": {
		"friendly": 400,
		"teaching": 400,
		"leader": 400
	},
	"report": {
		"aimbot":20,
		"wallhack": 20,
		"speedhack": 20,
		"teamharm": 20,
		"abusive": 20
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "commend",
	"method": "server",
	"target": "",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "",
	"disableUpdateCheck": false
}



enter "enter" in cmd, it won't continue

**Comment by BeepIsla** [comment]
Need more logs, from start to finish, there seems to be an issue with one specific account for some reason and I need to know if the account is in the process of logging in, successfully logged in but can't authenticate, or whatever else exactly happens.

**Comment by crx9** [comment]
> Need more logs, from start to finish, there seems to be an issue with one specific account for some reason and I need to know if the account is in the process of logging in, successfully logged in but can't authenticate, or whatever else exactly happens.

I closed it  ,I'll give it to you next time

**Comment by crx9** [comment]
[13333664411] Logged onto Steam - GC Time: 2020-3-2 0:29:30
 [13275172142] Logged onto Steam - GC Time: 2020-3-2 0:29:30
 [13278917173] Logged onto Steam - GC Time: 2020-3-2 0:29:30
 [13333664411] Authenticated to anonymous server with ticket 3604713143
 [13275172142] Authenticated to anonymous server with ticket 2340125421
 [13333664411] Successfully sent a commend with response code 1 - Remaining Commends: 2 (1/20)
 [13262953227] Logged onto Steam - GC Time: 2020-3-2 0:29:31
 [1329941095] Logged onto Steam - GC Time: 2020-3-2 0:29:31
 [13275172142] Successfully sent a commend with response code 1 - Remaining Commends: 2 (2/20)
 [13278917173] Authenticated to anonymous server with ticket 3823493419
 [13278917173] Successfully sent a commend with response code 1 - Remaining Commends: 2 (3/20)
 [133370712] Logged onto Steam - GC Time: 2020-3-2 0:29:33
 [1329941095] Authenticated to anonymous server with ticket 2715929148
 [1325685831] Logged onto Steam - GC Time: 2020-3-2 0:29:34
 [13305106980] Logged onto Steam - GC Time: 2020-3-2 0:29:32
 [13262953227] Authenticated to anonymous server with ticket 2371164767
 [133370712] Authenticated to anonymous server with ticket 937362493
 [1329941095] Successfully sent a commend with response code 1 - Remaining Commends: 2 (4/20)
 [13262953227] Successfully sent a commend with response code 1 - Remaining Commends: 2 (5/20)
 [13332228119] Logged onto Steam - GC Time: 2020-3-2 0:29:34
 [13259949569] Logged onto Steam - GC Time: 2020-3-2 0:29:34
 [13336261114] Logged onto Steam - GC Time: 2020-3-2 0:29:34
 [1325685831] Authenticated to anonymous server with ticket 3749736477
 [133370712] Successfully sent a commend with response code 1 - Remaining Commends: 2 (6/20)
 [1334104311] Logged onto Steam - GC Time: 2020-3-2 0:29:34
 [13253925909] Logged onto Steam - GC Time: 2020-3-2 0:29:34
 [1334797577] Logged onto Steam - GC Time: 2020-3-2 0:29:34
 [13309789206] Logged onto Steam - GC Time: 2020-3-2 0:29:35
 [13305106980] Authenticated to anonymous server with ticket 2400373665
 [13260423647] Logged onto Steam - GC Time: 2020-3-2 0:29:30
 [1325685831] Successfully sent a commend with response code 1 - Remaining Commends: 2 (7/20)
 [13310087080] Logged onto Steam - GC Time: 2020-3-2 0:29:35
 [13321119468] Logged onto Steam - GC Time: 2020-3-2 0:29:35
 [13332228119] Authenticated to anonymous server with ticket 546526728
 [13259949569] Authenticated to anonymous server with ticket 1590302400
 [13305106980] Successfully sent a commend with response code 1 - Remaining Commends: 2 (8/20)
 [13336261114] Authenticated to anonymous server with ticket 1316862998
 [13309789206] Authenticated to anonymous server with ticket 2149630726
 [13253925909] Authenticated to anonymous server with ticket 612579500
 [1334104311] Authenticated to anonymous server with ticket 363056582
 [1334797577] Authenticated to anonymous server with ticket 3778761067
 [13270352520] Logged onto Steam - GC Time: 2020-3-2 0:29:35
 [13332228119] Successfully sent a commend with response code 1 - Remaining Commends: 2 (9/20)
 [13259949569] Successfully sent a commend with response code 1 - Remaining Commends: 2 (10/20)
 [13336261114] Successfully sent a commend with response code 1 - Remaining Commends: 2 (11/20)
 [13309789206] Successfully sent a commend with response code 1 - Remaining Commends: 2 (12/20)
 [13253925909] Successfully sent a commend with response code 1 - Remaining Commends: 2 (13/20)
 [1334104311] Successfully sent a commend with response code 1 - Remaining Commends: 2 (14/20)
 [1334797577] Successfully sent a commend with response code 1 - Remaining Commends: 2 (15/20)
 [13321119468] Authenticated to anonymous server with ticket 2703546171
 [13310087080] Authenticated to anonymous server with ticket 4053537660
 [13321119468] Successfully sent a commend with response code 1 - Remaining Commends: 2 (16/20)
 [13310087080] Successfully sent a commend with response code 1 - Remaining Commends: 2 (17/20)
 [13270352520] Authenticated to anonymous server with ticket 2043659146
 [13270352520] Successfully sent a commend with response code 1 - Remaining Commends: 2 (18/20)
 [1332591595] Failed to login and has been marked as invalid (19/20) {
  name: 'Error',
  message: 'GC connection timeout - MMHello',
  stack: 'Error: GC connection timeout - MMHello\n' +
    '    at

**Comment by BeepIsla** [comment]
Not enough, need more. There needs to be everything from start to end, most importantly `[Name] Logging into Steam...`, `[Name] Logged onto Steam`, `[Name] Authenticated to anonymous server with ticket` and `[Name] Successfully sent a commend`. As those will exactly tell me where in the code the issue occurs.

**Comment by crx9** [comment]
Successfully authenticated to anonymous server with ticket 1873578693
 Logging in on chunk 3/125
 [13253925909] Logging into Steam
 [1325685831] Logging into Steam
 [13259949569] Logging into Steam
 [13260423647] Logging into Steam
 [13262953227] Logging into Steam
 [13270352520] Logging into Steam
 [13275172142] Logging into Steam
 [13278917173] Logging into Steam
 [1329941095] Logging into Steam
 [13305106980] Logging into Steam
 [13309789206] Logging into Steam
 [13310087080] Logging into Steam
 [13321119468] Logging into Steam
 [1332591595] Logging into Steam
 [13332228119] Logging into Steam
 [13333664411] Logging into Steam
 [13336261114] Logging into Steam
 [133370712] Logging into Steam
 [1334104311] Logging into Steam
 [1334797577] Logging into Steam
[13333664411] Logged onto Steam - GC Time: 2020-3-2 0:29:30
[13275172142] Logged onto Steam - GC Time: 2020-3-2 0:29:30
[13278917173] Logged onto Steam - GC Time: 2020-3-2 0:29:30
[13333664411] Authenticated to anonymous server with ticket 3604713143
[13275172142] Authenticated to anonymous server with ticket 2340125421
[13333664411] Successfully sent a commend with response code 1 - Remaining Commends: 2 (1/20)
[13262953227] Logged onto Steam - GC Time: 2020-3-2 0:29:31
[1329941095] Logged onto Steam - GC Time: 2020-3-2 0:29:31
[13275172142] Successfully sent a commend with response code 1 - Remaining Commends: 2 (2/20)
[13278917173] Authenticated to anonymous server with ticket 3823493419
[13278917173] Successfully sent a commend with response code 1 - Remaining Commends: 2 (3/20)
[133370712] Logged onto Steam - GC Time: 2020-3-2 0:29:33
[1329941095] Authenticated to anonymous server with ticket 2715929148
[1325685831] Logged onto Steam - GC Time: 2020-3-2 0:29:34
[13305106980] Logged onto Steam - GC Time: 2020-3-2 0:29:32
[13262953227] Authenticated to anonymous server with ticket 2371164767
[133370712] Authenticated to anonymous server with ticket 937362493
[1329941095] Successfully sent a commend with response code 1 - Remaining Commends: 2 (4/20)
[13262953227] Successfully sent a commend with response code 1 - Remaining Commends: 2 (5/20)
[13332228119] Logged onto Steam - GC Time: 2020-3-2 0:29:34
[13259949569] Logged onto Steam - GC Time: 2020-3-2 0:29:34
[13336261114] Logged onto Steam - GC Time: 2020-3-2 0:29:34
[1325685831] Authenticated to anonymous server with ticket 3749736477
[133370712] Successfully sent a commend with response code 1 - Remaining Commends: 2 (6/20)
[1334104311] Logged onto Steam - GC Time: 2020-3-2 0:29:34
[13253925909] Logged onto Steam - GC Time: 2020-3-2 0:29:34
[1334797577] Logged onto Steam - GC Time: 2020-3-2 0:29:34
[13309789206] Logged onto Steam - GC Time: 2020-3-2 0:29:35
[13305106980] Authenticated to anonymous server with ticket 2400373665
[13260423647] Logged onto Steam - GC Time: 2020-3-2 0:29:30
[1325685831] Successfully sent a commend with response code 1 - Remaining Commends: 2 (7/20)
[13310087080] Logged onto Steam - GC Time: 2020-3-2 0:29:35
[13321119468] Logged onto Steam - GC Time: 2020-3-2 0:29:35
[13332228119] Authenticated to anonymous server with ticket 546526728
[13259949569] Authenticated to anonymous server with ticket 1590302400
[13305106980] Successfully sent a commend with response code 1 - Remaining Commends: 2 (8/20)
[13336261114] Authenticated to anonymous server with ticket 1316862998
[13309789206] Authenticated to anonymous server with ticket 2149630726
[13253925909] Authenticated to anonymous server with ticket 612579500
[1334104311] Authenticated to anonymous server with ticket 363056582
[1334797577] Authenticated to anonymous server with ticket 3778761067
[13270352520] Logged onto Steam - GC Time: 2020-3-2 0:29:35
[13332228119] Successfully sent a commend with response code 1 - Remaining Commends: 2 (9/20)
[13259949569] Successfully sent a commend with response code 1 - Remaining Commends: 2 (10/20)
[13336261114] Successfully sent a commend with response code 1 - Remaining Commends: 2 (11/20)
[13309789206] Successfully sent a commend with response code 1 - Remaining Commends: 2 (12/20)
[13253925909] Successfully sent a commend with response code 1 - Remaining Commends: 2 (13/20)
[1334104311] Successfully sent a commend with response code 1 - Remaining Commends: 2 (14/20)
[1334797577] Successfully sent a commend with response code 1 - Remaining Commends: 2 (15/20)
[13321119468] Authenticated to anonymous server with ticket 2703546171
[13310087080] Authenticated to anonymous server with ticket 4053537660
[13321119468] Successfully sent a commend with response code 1 - Remaining Commends: 2 (16/20)
[13310087080] Successfully sent a commend with response code 1 - Remaining Commends: 2 (17/20)
[13270352520] Authenticated to anonymous server with ticket 2043659146
[13270352520] Successfully sent a commend with response code 1 - Remaining Commends: 2 (18/20)
[1332591595] Failed to login and has been marked as invalid (19/20) {
name: 'Error',
message: 'GC connection timeout - MMHello',
stack: 'Error: GC connection timeout - MMHello\n' +
' at

**Comment by crx9** [comment]
message: 'GC connection timeout - MMHello',

**Comment by BeepIsla** [comment]
> [13260423647] Logging into Steam
> [13260423647] Logged onto Steam - GC Time: 2020-3-2 0:29:30

And that's it, this is where that account stops. It should timeout after up to 30 seconds though. Does it not?

**Comment by crx9** [comment]
> > [13260423647] Logging into Steam [13260423647] Logged onto Steam - GC Time: 2020-3-2 0:29:30
> 
> And that's it, this is where that account stops. It should timeout after up to 30 seconds though. Does it not?

these are all the logs. I dont konw what happend

**Comment by crx9** [comment]
Waiting 300000ms...
 Logging in on chunk 9/10
 [syrj0303] Logging into Steam
 [sys1819] Logging into Steam
 [sys4561] Logging into Steam
 [sysh521] Logging into Steam
 [sysien8042] Logging into Steam
 [sysloading] Logging into Steam
 [syt162412] Logging into Steam
 [syw9460] Logging into Steam
 [syy0680] Logging into Steam
 [syy722926] Logging into Steam
 [syycrazy] Logging into Steam
 [syyw317214095] Logging into Steam
 [sz124556817] Logging into Steam
 [sz273639202] Logging into Steam
 [sz81506756] Logging into Steam
 [sz9450519] Logging into Steam
 [szbabysit] Logging into Steam
 [szgvzyl] Logging into Steam
 [szicewind] Logging into Steam
 [szq9640] Logging into Steam
 [syycrazy] Failed to login and has been marked as invalid (1/20) {
  eresult: 5,
  name: 'Error',
  message: 'InvalidPassword',
  stack: 'Error: InvalidPassword\n' +
    '    at SteamUser.<anonymous> (F:\\1\\node_modules\\steam-user\\components\\logon.js:458:16)\n' +
    '    at F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:545:24)\n' +
    '    at SteamUser.Coordinator.steamUser._handleMessage (F:\\1\\helpers\\GameCoordinator.js:43:19)\n' +
    '    at SteamUser._handleNetMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:480:7)\n' +
    '    at SteamUser.processMulti (F:\\1\\node_modules\\steam-user\\components\\messages.js:572:9)\n' +
    '    at SteamUser.<anonymous> (F:\\1\\node_modules\\steam-user\\components\\messages.js:566:16)\n' +
    '    at F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12'
}
 [sysien8042] Requires a Steam Guard code and has been marked as invalid (2/20) {
  name: 'Error',
  message: 'Steam Guard required',
  stack: 'Error: Steam Guard required\n' +
    '    at SteamUser.steamGuard (F:\\1\\helpers\\account.js:180:12)\n' +
    '    at SteamUser.emit (events.js:209:13)\n' +
    '    at SteamUser._steamGuardPrompt (F:\\1\\node_modules\\steam-user\\components\\logon.js:570:8)\n' +
    '    at SteamUser.<anonymous> (F:\\1\\node_modules\\steam-user\\components\\logon.js:432:9)\n' +
    '    at F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:545:24)\n' +
    '    at SteamUser.Coordinator.steamUser._handleMessage (F:\\1\\helpers\\GameCoordinator.js:43:19)\n' +
    '    at SteamUser._handleNetMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:480:7)'
}
 [sysloading] Requires a Steam Guard code and has been marked as invalid (3/20) {
  name: 'Error',
  message: 'Steam Guard required',
  stack: 'Error: Steam Guard required\n' +
    '    at SteamUser.steamGuard (F:\\1\\helpers\\account.js:180:12)\n' +
    '    at SteamUser.emit (events.js:209:13)\n' +
    '    at SteamUser._steamGuardPrompt (F:\\1\\node_modules\\steam-user\\components\\logon.js:570:8)\n' +
    '    at SteamUser.<anonymous> (F:\\1\\node_modules\\steam-user\\components\\logon.js:432:9)\n' +
    '    at F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:545:24)\n' +
    '    at SteamUser.Coordinator.steamUser._handleMessage (F:\\1\\helpers\\GameCoordinator.js:43:19)\n' +
    '    at SteamUser._handleNetMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:480:7)'
}
 [sysh521] Failed to login and has been marked as invalid (4/20) {
  eresult: 5,
  name: 'Error',
  message: 'InvalidPassword',
  stack: 'Error: InvalidPassword\n' +
    '    at SteamUser.<anonymous> (F:\\1\\node_modules\\steam-user\\components\\logon.js:458:16)\n' +
    '    at F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:545:24)\n' +
    '    at SteamUser.Coordinator.steamUser._handleMessage (F:\\1\\helpers\\GameCoordinator.js:43:19)\n' +
    '    at SteamUser._handleNetMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:480:7)\n' +
    '    at SteamUser.processMulti (F:\\1\\node_modules\\steam-user\\components\\messages.js:572:9)\n' +
    '    at SteamUser.<anonymous> (F:\\1\\node_modules\\steam-user\\components\\messages.js:566:16)\n' +
    '    at F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12'
}
 [syw9460] Failed to login and has been marked as invalid (5/20) {
  eresult: 5,
  name: 'Error',
  message: 'InvalidPassword',
  stack: 'Error: InvalidPassword\n' +
    '    at SteamUser.<anonymous> (F:\\1\\node_modules\\steam-user\\components\\logon.js:458:16)\n' +
    '    at F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:545:24)\n' +
    '    at SteamUser.Coordinator.steamUser._handleMessage (F:\\1\\helpers\\GameCoordinator.js:43:19)\n' +
    '    at SteamUser._handleNetMessage (F:\\1\\node_modules\\steam-user\\components\\messages.js:480:7)\n' +
    '    at SteamUser.processMulti (F:\\1\\node_modules\\steam-user\\components\\messages.js:572:9)\n' +
    '    at SteamUser.<anonymous> (F:\\1\\node_modules\\steam-user\\components\\messages.js:566:16)\n' +
    '    at F:\\1\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12'
}
 [sys4561] Logged onto Steam - GC Time: 2020-3-2 1:31:00
 [sys4561] Authenticated to anonymous server with ticket 2648396347
 [sys4561] Successfully sent a commend with response code 1 - Remaining Commends: 2 (6/20)
 [szbabysit] Logged onto Steam - GC Time: 2020-3-2 1:31:04
 [szbabysit] Authenticated to anonymous server with ticket 1084486437
 [szgvzyl] Logged onto Steam - GC Time: 2020-3-2 1:31:03
 [szbabysit] Successfully sent a commend with response code 1 - Remaining Commends: 2 (7/20)
 [szq9640] Logged onto Steam - GC Time: 2020-3-2 1:31:05
 [szgvzyl] Authenticated to anonymous server with ticket 1898648185
 [sz273639202] Logged onto Steam - GC Time: 2020-3-2 1:31:06
 [szq9640] Authenticated to anonymous server with ticket 3776494135
 [syrj0303] Logged onto Steam - GC Time: 2020-3-2 1:31:07
 [szicewind] Logged onto Steam - GC Time: 2020-3-2 1:31:07
 [syy722926] Logged onto Steam - GC Time: 2020-3-2 1:31:07
 [szgvzyl] Successfully sent a commend with response code 1 - Remaining Commends: 2 (8/20)
 [sz124556817] Logged onto Steam - GC Time: 2020-3-2 1:31:07
 [syy0680] Logged onto Steam - GC Time: 2020-3-2 1:31:07
 [szq9640] Successfully sent a commend with response code 1 - Remaining Commends: 2 (9/20)
 [sz273639202] Authenticated to anonymous server with ticket 3441285364
 [sz81506756] Logged onto Steam - GC Time: 2020-3-2 1:31:07
 [syyw317214095] Logged onto Steam - GC Time: 2020-3-2 1:31:07
 [syrj0303] Authenticated to anonymous server with ticket 1554501832
 [sz273639202] Successfully sent a commend with response code 1 - Remaining Commends: 2 (10/20)
 [syy0680] Authenticated to anonymous server with ticket 2273168615
 [sz124556817] Authenticated to anonymous server with ticket 275432848
 [syy722926] Authenticated to anonymous server with ticket 4232613857
 [szicewind] Authenticated to anonymous server with ticket 1342084734
 [syrj0303] Successfully sent a commend with response code 1 - Remaining Commends: 2 (11/20)
 [syy0680] Successfully sent a commend with response code 1 - Remaining Commends: 2 (12/20)
 [sz81506756] Authenticated to anonymous server with ticket 1465476417
 [syyw317214095] Authenticated to anonymous server with ticket 4070998781
 [syy722926] Successfully sent a commend with response code 1 - Remaining Commends: 2 (13/20)
 [sz124556817] Successfully sent a commend with response code 1 - Remaining Commends: 2 (14/20)
 [szicewind] Successfully sent a commend with response code 1 - Remaining Commends: 2 (15/20)
 [sz9450519] Logged onto Steam - GC Time: 2020-3-2 1:31:07
 [sz81506756] Successfully sent a commend with response code 1 - Remaining Commends: 2 (16/20)
 [syyw317214095] Successfully sent a commend with response code 1 - Remaining Commends: 2 (17/20)
 [sys1819] Failed to login and has been marked as invalid (18/20) {
  name: 'Error',
  message: 'GC connection timeout - MMHello',
  stack: 'Error: GC connection timeout - MMHello\n' +
    '    at F:\\1\\helpers\\account.js:167:13'
}
 [syt162412] Logged onto Steam - GC Time: 2020-3-2 1:31:35
 [syt162412] Authenticated to anonymous server with ticket 1860070572
 [syt162412] Successfully sent a commend with response code 1 - Remaining Commends: 2 (19/20)



19/20  .stopped.....

**Comment by BeepIsla** [comment]
Same issue here, I think I found the problem but I am unsure. I will push a fix and let you try it out.

**Comment by BeepIsla** [comment]
Okay, I have pushed a potential fix for it (3350c561bea155b77327bec03fa0fe1bb77ad520) please update and try if it still happens.

**Comment by crx9** [comment]
> Okay, I have pushed a potential fix for it ([3350c56](https://github.com/BeepIsla/csgo-commend-bot/commit/3350c561bea155b77327bec03fa0fe1bb77ad520)) please update and try if it still happens.

Worked.It doesn't stop at 19/20  (GC connection timeout)
