### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by yxw770** [BeepIsla/csgo-commend-bot#280]
[91qlf0035] Authenticated to anonymous server with ticket 619188412 
 [91qlf0036] Successfully sent a commend with response code 1 - Remaining Commends: 1 (7/10) 
(node:32114) UnhandledPromiseRejectionWarning: TypeError: serializeError.serializeError is not a function
    at /home/csgo/helpers/Bots.js:115:28
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:32114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:32114) UnhandledPromiseRejectionWarning: TypeError: serializeError.serializeError is not a function
    at /home/csgo/helpers/Bots.js:115:28
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:32114) UnhandledPromiseRejectionWarning: TypeError: serializeError.serializeError is not a function
    at /home/csgo/helpers/Bots.js:115:28
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)

**Comment by yxw770** [comment]
Chunk 3/92 finished with 10 successful commends and 0 failed commends 
 Waiting 125000ms... 
 Successfully authenticated to anonymous server with ticket 939757444 
 Logging in on chunk 4/92 
 [91qlf0034] Logging into Steam 
 [91qlf0035] Logging into Steam 
 [91qlf0036] Logging into Steam 
 [91qlf0037] Logging into Steam 
 [91qlf0038] Logging into Steam 
 [91qlf0039] Logging into Steam 
 [91qlf0040] Logging into Steam 
 [91qlf0041] Logging into Steam 
 [91qlf0042] Logging into Steam 
 [91qlf0043] Logging into Steam 
 [91qlf0034] Logged onto Steam - GC Time: 3/2/2020, 11:04:47 AM 
 [91qlf0037] Logged onto Steam - GC Time: 3/2/2020, 11:04:47 AM 
 [91qlf0043] Logged onto Steam - GC Time: 3/2/2020, 11:04:47 AM 
 [91qlf0040] Logged onto Steam - GC Time: 3/2/2020, 11:04:47 AM 
 [91qlf0038] Logged onto Steam - GC Time: 3/2/2020, 11:04:47 AM 
 [91qlf0037] Authenticated to anonymous server with ticket 1794235701 
 [91qlf0034] Authenticated to anonymous server with ticket 3358004090 
 [91qlf0042] Logged onto Steam - GC Time: 3/2/2020, 11:04:47 AM 
 [91qlf0043] Authenticated to anonymous server with ticket 3482756763 
 [91qlf0039] Logged onto Steam - GC Time: 3/2/2020, 11:04:47 AM 
 [91qlf0040] Authenticated to anonymous server with ticket 1077667960 
 [91qlf0041] Logged onto Steam - GC Time: 3/2/2020, 11:04:47 AM 
 [91qlf0038] Authenticated to anonymous server with ticket 3163369793 
 [91qlf0042] Authenticated to anonymous server with ticket 587423379 
 [91qlf0037] Successfully sent a commend with response code 1 - Remaining Commends: 1 (1/10) 
 [91qlf0040] Successfully sent a commend with response code 1 - Remaining Commends: 1 (2/10) 
 [91qlf0043] Successfully sent a commend with response code 1 - Remaining Commends: 1 (3/10) 
 [91qlf0039] Authenticated to anonymous server with ticket 842012833 
 [91qlf0041] Authenticated to anonymous server with ticket 3465770673 
 [91qlf0042] Successfully sent a commend with response code 1 - Remaining Commends: 1 (4/10) 
 [91qlf0039] Successfully sent a commend with response code 1 - Remaining Commends: 1 (5/10) 
 [91qlf0041] Successfully sent a commend with response code 1 - Remaining Commends: 1 (6/10) 
 [91qlf0036] Logged onto Steam - GC Time: 3/2/2020, 11:04:50 AM 
 [91qlf0036] Authenticated to anonymous server with ticket 863192585 
 [91qlf0035] Logged onto Steam - GC Time: 3/2/2020, 11:04:51 AM 
 [91qlf0035] Authenticated to anonymous server with ticket 619188412 
 [91qlf0036] Successfully sent a commend with response code 1 - Remaining Commends: 1 (7/10) 
(node:32114) UnhandledPromiseRejectionWarning: TypeError: serializeError.serializeError is not a function
    at /home/csgo/helpers/Bots.js:115:28
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:32114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:32114) UnhandledPromiseRejectionWarning: TypeError: serializeError.serializeError is not a function
    at /home/csgo/helpers/Bots.js:115:28
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:32114) UnhandledPromiseRejectionWarning: TypeError: serializeError.serializeError is not a function
    at /home/csgo/helpers/Bots.js:115:28
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)

**Comment by yxw770** [comment]
![image](https://user-images.githubusercontent.com/10827451/75644723-2d11d700-5c7e-11ea-85f8-1a28d2e82e3c.png)

**Comment by yxw770** [comment]
![image](https://user-images.githubusercontent.com/10827451/75644751-43b82e00-5c7e-11ea-830d-a255bca8d0c3.png)

**Comment by BeepIsla** [comment]
Update your modules using `npm update` or `npm install`
