### ISSUE TITLE
Error while logging in to steam

### ISSUE THREAD

**Issue by LegendFTW1** [BeepIsla/csgo-commend-bot#284]
**Detailed bug description**
I get the error down there when I start the bot. Is this error from the bot or smth else?
**Error**
```
[d2RsNGh8DUef] Authenticated to anonymous server with ticket 2610981704
 [d2RsNGh8DUef] Failed to login and has been marked as invalid (14/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\eyad_\\Downloads\\csgo-commend-bot-master\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
```

**Config**
```
{
	"commend": {
		"friendly": 15,
		"teaching": 15,
		"leader": 15
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/eyad16/",
	"perChunk": 20,
	"betweenChunks": 50000,
	"cooldown": 28800000,
	"steamWebAPIKey": "X",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v10.14.2`
- Script version: `2.7.1`

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Update your `node_modules` using `npm update` or `npm install`
