### ISSUE TITLE
TypeError: Cannot read property 'accountid' of nul

### ISSUE THREAD

**Issue by crx9** [BeepIsla/csgo-commend-bot#290]
Waiting 300000 ms...
Error: Failed to send message: Timeout
    at Timeout._onTimeout (F:\1\helpers\GameCoordinator.js:82:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Logging in on chunk 14/15
TypeError: Cannot read property 'accountid' of null
    at Target.get accountid [as accountid] (F:\1\helpers\Target.js:10:37)
    at F:\1\index.js:296:49 Promise {
  <rejected> TypeError: Cannot read property 'accountid' of null
      at Target.get accountid [as accountid] (F:\1\helpers\Target.js:10:37)
      at F:\1\index.js:296:49

**Comment by BeepIsla** [comment]
Target account lost connection to Steam during commending process
