### ISSUE TITLE
how to solve error 429?

### ISSUE THREAD

**Issue by csgocommends** [BeepIsla/csgo-commend-bot#309]
Error: Invalid Status Code: 429
    at Request._callback (D:\commend bot\csgo-commend-bot-master\helpers\Helper.js:229:12)
    at Request.self.callback (D:\commend bot\csgo-commend-bot-master\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (D:\commend bot\csgo-commend-bot-master\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (D:\commend bot\csgo-commend-bot-master\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

how to solve this problem? I cant commends so I try reinstall nodejs and 'csgo-commend-bot-master' but still can see this error.

**Comment by BeepIsla** [comment]
429: https://httpstatuses.com/429

You have restarted too many times, either Github or Steam are blocking your requests.

**Comment by csgocommends** [comment]
can I use it when wait long time? I tried by little account but I cant

**Comment by BeepIsla** [comment]
Just wait and try again later. I don't know how long you have to wait. Check if it works in an hour or two.

**Comment by csgocommends** [comment]
steam was blocked 1 day thanks It works now
