### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by robertplanet** [BeepIsla/csgo-commend-bot#310]
TypeError: Cannot read property 'toUpperCase' of undefined
    at C:\Users\banea\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:76:50
    at Object.<anonymous> (C:\Users\banea\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:318:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 Promise {
  <rejected> TypeError: Cannot read property 'toUpperCase' of undefined
      at C:\Users\banea\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:76:50
      at Object.<anonymous> (C:\Users\banea\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:318:3)
      at Module._compile (internal/modules/cjs/loader.js:1158:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
      at Module.load (internal/modules/cjs/loader.js:1002:32)
      at Function.Module._load (internal/modules/cjs/loader.js:901:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
      at internal/main/run_main_module.js:18:47

"commend": {
		"friendly": 1265,
		"teaching": 1265,
		"leader": 1265
	},"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	
	},
	"fetcher": {
		"username": "robertpt",
		"password": "bob2005",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/MM_LEGEND/",
	"serverID": "145.239.136.33:27050",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "EACC96D30D301FBC8B661"

**Comment by BeepIsla** [comment]
Follow the issue template. Show your config.

**Comment by robertplanet** [comment]
> Follow the issue template. Show your config.

ready

**Comment by BeepIsla** [comment]
Are you using a really old version? `fetcher` has not existed for a long time.

**Comment by robertplanet** [comment]
no is just downloaded

**Comment by robertplanet** [comment]
do u have discord?

**Comment by BeepIsla** [comment]
I do have Discord but I stopped giving it to people.

---

Your config includes `fetcher` which no longer exists and `type` seems to be missing too. Make sure you download from `master` and not from a previous commit. Try again downloading from [this](https://github.com/BeepIsla/csgo-commend-bot/archive/master.zip) link and create your config from scratch following the example again.

If you already know how JSON works you can also just try adding a `type` key and set its value to `"COMMEND"`.

**Comment by robertplanet** [comment]
ok

**Comment by robertplanet** [comment]
thx for help now is working
