### ISSUE TITLE
Error while use proxy

### ISSUE THREAD

**Issue by MAAAZee** [BeepIsla/csgo-commend-bot#311]
I have a mistake wehen i use proxy please help me

Parsing target account...
 Chunking 50 accounts into groups of 20...
 Logging in on chunk 1/3
 [0oempetoi4pG] Logging into Steam
 [17BURA3QhB7A] Logging into Steam
 [1HTRGvjbImQi] Logging into Steam
 [1nw3LvgB16EV] Logging into Steam
 [23HW8S5JOcCw] Logging into Steam
 [2peMe6Nao2d0] Logging into Steam
 [2xC4OWf8riPO] Logging into Steam
 [539GVMSOEzhC] Logging into Steam
 [5S0TAtTXQWH2] Logging into Steam
 [5wavrKxPgXbJ] Logging into Steam
 [61TMfoXAdbxE] Logging into Steam
 [7Na6wIaHWTR7] Logging into Steam
 [7oXcFPQYZuqG] Logging into Steam
 [8bv8ajUmmysA] Logging into Steam
 [8qIwfphnDvvl] Logging into Steam
 [9RTj8POaG3Wu] Logging into Steam
 [BNzongEhwpWw] Logging into Steam
 [DS8s7TgzcVLg] Logging into Steam
 [EGa145mzyKHU] Logging into Steam
 [FqYjxyB1e19y] Logging into Steam
(node:6184) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Host"]
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:261:12)
    at Object.request (http.js:46:10)
    at Agent.agent.createConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\@doctormckay\stdlib\components\http\proxyagent.js:42:56)
    at Agent.createSocket (_http_agent.js:265:26)
    at Agent.addRequest (_http_agent.js:224:10)
    at new ClientRequest (_http_client.js:296:16)
    at request (https.js:314:10)
    at Object.get (https.js:318:15)
    at WebSocketConnection._pingCM (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\websocket.js:207:8)
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 81)
(node:6184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6184) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Host"]
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:261:12)
    at Object.request (http.js:46:10)
    at new TCPConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:45:18)
    at SteamUser._doConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:238:23)
    at C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:218:8
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 82)
(node:6184) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Host"]
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:261:12)
    at Object.request (http.js:46:10)
    at new TCPConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:45:18)
    at SteamUser._doConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:238:23)
    at C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:218:8
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 83)
(node:6184) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Host"]
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:261:12)
    at Object.request (http.js:46:10)
    at new TCPConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:45:18)
    at SteamUser._doConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:238:23)
    at C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:218:8
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 84)
(node:6184) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Host"]
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:261:12)
    at Object.request (http.js:46:10)
    at new TCPConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:45:18)
    at SteamUser._doConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:238:23)
    at C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:218:8
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 85)
(node:6184) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Host"]
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:261:12)
    at Object.request (http.js:46:10)
    at new TCPConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:45:18)
    at SteamUser._doConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:238:23)
    at C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:218:8
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 86)
(node:6184) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Host"]
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:261:12)
    at Object.request (http.js:46:10)
    at new TCPConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:45:18)
    at SteamUser._doConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:238:23)
    at C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:218:8
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 87)
(node:6184) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Host"]
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:261:12)
    at Object.request (http.js:46:10)
    at new TCPConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:45:18)
    at SteamUser._doConnection (C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:238:23)
    at C:\Users\User\Desktop\egzot (200)\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:218:8
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 88)

**Comment by BeepIsla** [comment]
Read the error, your proxy list has an invalid character in it.
