### ISSUE TITLE
[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function

### ISSUE THREAD

**Issue by sherlockparadox** [BeepIsla/csgo-commend-bot#342]
**Detailed bug description**
Stack Trace says 

**Error**
```
 [emily2015ford] Logged onto Steam - GC Time: 4/8/2020, 7:15:09 PM 
 [emily2015ford] Authenticated to anonymous server with ticket 1624837600 
 [emily2015ford] Failed to login and has been marked as invalid (20/20) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (/Users/archit/Documents/CSGO_Commend_Bot/bot/Commend_Bot/csgo-commend-bot/helpers/Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' } 
```

**Config**
```
{
	"commend": {
		"friendly": 100,
		"teaching": 100,
		"leader": 100
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/XXXXXXXXXXX",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "XXXXXXXXXXXXXXXXXX",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
Install NodeJS v12.

**Comment by sherlockparadox** [comment]
I'll try that. Really appreciate your quick response man. Cheers!
