### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/csgo-commend-bot#348]
`I took him again and he does the same` 

[code]
$ node index
SyntaxError: C:\Users\--\Desktop\Commends\config.json: Unexpected token

 in JSON at position 440
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:961:27)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at C:\Users\--\Desktop\Commends\index.js:46:12
    at Object.<anonymous> (C:\Users\--\Desktop\Commends\index.js:318:3)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
[/code]

**Comment by BeepIsla** [comment]
Fix your config. It has an error in it.
