### ISSUE TITLE
Why i have that error?

### ISSUE THREAD

**Issue by MrDumox** [BeepIsla/csgo-commend-bot#352]
[Error:](url) Invalid Status Code: 400
    at Request._callback (C:\Users\Mateusz\Desktop\csgo-commend-bot-master (1)\csgo-commend-bot-master\helpers\Helper.js:229:12)
    at Request.self.callback (C:\Users\Mateusz\Desktop\csgo-commend-bot-master (1)\csgo-commend-bot-master\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (C:\Users\Mateusz\Desktop\csgo-commend-bot-master (1)\csgo-commend-bot-master\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (C:\Users\Mateusz\Desktop\csgo-commend-bot-master (1)\csgo-commend-bot-master\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

![image](https://user-images.githubusercontent.com/57267520/79334044-defc1e80-7f1f-11ea-8da7-d66129f2039e.png)

**Comment by BeepIsla** [comment]
What is your config

**Comment by MrDumox** [comment]
![xd](https://user-images.githubusercontent.com/57267520/79335739-cccfaf80-7f22-11ea-8fea-637ef22d6858.png)

**Comment by BeepIsla** [comment]
The only reason I can imagine is your having some special characters in it. Try using SteamID64

**Comment by MrDumox** [comment]
where? in target?

**Comment by BeepIsla** [comment]
Yes where else

**Comment by MrDumox** [comment]
Thanks already work <3
