### ISSUE TITLE
Error: Invalid Status Code: 500

### ISSUE THREAD

**Issue by rabell69** [BeepIsla/csgo-commend-bot#374]
Error: Invalid Status Code: 500 - Visit https://httpstatuses.com/500
    at Request._callback (C:\Users\rabell69\Desktop\bot\1\helpers\Helper.js:172:13)
    at Request.self.callback (C:\Users\rabell69\Desktop\bot\1\node_modules\request\request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.<anonymous> (C:\Users\rabell69\Desktop\bot\1\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:209:13)
    at IncomingMessage.<anonymous> (C:\Users\rabell69\Desktop\bot\1\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:297:20)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) Promise {
  <rejected> Error: Invalid Status Code: 500 - Visit https://httpstatuses.com/500
      at Request._callback (C:\Users\rabell69\Desktop\bot\1\helpers\Helper.js:172:13)
      at Request.self.callback (C:\Users\rabell69\Desktop\bot\1\node_modules\request\request.js:185:22)
      at Request.emit (events.js:209:13)
      at Request.<anonymous> (C:\Users\rabell69\Desktop\bot\1\node_modules\request\request.js:1154:10)
      at Request.emit (events.js:209:13)
      at IncomingMessage.<anonymous> (C:\Users\rabell69\Desktop\bot\1\node_modules\request\request.js:1076:12)
      at Object.onceWrapper (events.js:297:20)
      at IncomingMessage.emit (events.js:214:15)
      at endReadableNT (_stream_readable.js:1178:12)
      at processTicksAndRejections (internal/process/task_queues.js:77:11)

**Comment by BeepIsla** [comment]
#373
