### ISSUE TITLE
Use server commend ,Error: self signed certifica

### ISSUE THREAD

**Issue by crx9** [BeepIsla/csgo-commend-bot#400]
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
    at TLSSocket.emit (events.js:209:13)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}

**Comment by BeepIsla** [comment]
You have an invalid certificate installed for one of the requested URLs. You have to remove it. I can't help you with this, you have to find it yourself.
