### ISSUE TITLE
ERROR CAN'T COMMEND WITH ACCOUNTS

### ISSUE THREAD

**Issue by iKaros90** [BeepIsla/csgo-commend-bot#401]
**Detailed bug description**
I set the accounts in the data base (64 accs), and it get error all time. But all accounts work (i tested by myself)

**Error**
```
C:\Users\iKaros\Desktop\commend-reports>node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 39 operational accounts
 Parsing target account...
 Chunking 15 accounts into groups of 20...
 Logging in on chunk 1/1
 [irenebryan1991] Logging into Steam
 [isabel2016ishii] Logging into Steam
 [isabellacresti44] Logging into Steam
 [jayhines36] Logging into Steam
 [jaylucherini67] Logging into Steam
 [jeremiah48davey] Logging into Steam
 [jonmele2000] Logging into Steam
 [leahgentili1985] Logging into Steam
 [lelarenaud2014] Logging into Steam
 [logan2005wise] Logging into Steam
 [lucindacesari2011] Logging into Steam
 [marcjaspers1982] Logging into Steam
 [marion1982meier] Logging into Steam
 [masonnunez11] Logging into Steam
 [mathildarobertson4] Logging into Steam
 [isabel2016ishii] Logged onto Steam - GC Time: 2020-5-3 11:34:07 PM
 [jaylucherini67] Logged onto Steam - GC Time: 2020-5-3 11:34:08 PM
 [isabel2016ishii] Authenticated to anonymous server with ticket 1480245999
 [isabel2016ishii] Failed to login and has been marked as invalid (1/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [jayhines36] Logged onto Steam - GC Time: 2020-5-3 11:34:08 PM
 [jaylucherini67] Authenticated to anonymous server with ticket 19060042
 [jaylucherini67] Failed to login and has been marked as invalid (2/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [jayhines36] Authenticated to anonymous server with ticket 3821797371
 [jayhines36] Failed to login and has been marked as invalid (3/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [masonnunez11] Logged onto Steam - GC Time: 2020-5-3 11:34:12 PM
 [irenebryan1991] Logged onto Steam - GC Time: 2020-5-3 11:34:12 PM
 [mathildarobertson4] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [logan2005wise] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [masonnunez11] Authenticated to anonymous server with ticket 2157717206
 [masonnunez11] Failed to login and has been marked as invalid (4/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [lucindacesari2011] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [marion1982meier] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [marcjaspers1982] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [isabellacresti44] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [jonmele2000] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [lelarenaud2014] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [leahgentili1985] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [irenebryan1991] Authenticated to anonymous server with ticket 3639669419
 [irenebryan1991] Failed to login and has been marked as invalid (5/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [logan2005wise] Authenticated to anonymous server with ticket 1093430846
 [logan2005wise] Failed to login and has been marked as invalid (6/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [lucindacesari2011] Authenticated to anonymous server with ticket 3149338943
 [lucindacesari2011] Failed to login and has been marked as invalid (7/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [mathildarobertson4] Authenticated to anonymous server with ticket 3783237554
 [mathildarobertson4] Failed to login and has been marked as invalid (8/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [marion1982meier] Authenticated to anonymous server with ticket 3261672076
 [marion1982meier] Failed to login and has been marked as invalid (9/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [jeremiah48davey] Logged onto Steam - GC Time: 2020-5-3 11:34:13 PM
 [jonmele2000] Authenticated to anonymous server with ticket 3665348412
 [jonmele2000] Failed to login and has been marked as invalid (10/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [marcjaspers1982] Authenticated to anonymous server with ticket 1482036138
 [marcjaspers1982] Failed to login and has been marked as invalid (11/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [lelarenaud2014] Authenticated to anonymous server with ticket 780508162
 [lelarenaud2014] Failed to login and has been marked as invalid (12/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [leahgentili1985] Authenticated to anonymous server with ticket 2941811430
 [leahgentili1985] Failed to login and has been marked as invalid (13/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [isabellacresti44] Authenticated to anonymous server with ticket 1078401212
 [isabellacresti44] Failed to login and has been marked as invalid (14/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [jeremiah48davey] Authenticated to anonymous server with ticket 1881274320
 [jeremiah48davey] Failed to login and has been marked as invalid (15/15) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\iKaros\\Desktop\\commend-reports\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 Chunk 1/1 finished with 0 successful commends and 15 failed commends
 Finished all chunks with a total of 0 successful and 15 failed commends
```

**Config**
```
{
	"commend": {
		"friendly": 15,
		"teaching": 15,
		"leader": 15
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/guapetona/",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "MYAPIKEY",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v10.16.3` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
As per README:

> # Requirements
> 
> - [NodeJS **v12**](https://nodejs.org/)

**Comment by iKaros90** [comment]
C:\Users\iKaros\Desktop\commend-reports>node databasemanager.js
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'C:\Users\iKaros\Desktop\commend-reports\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node'
Require stack:
- C:\Users\iKaros\Desktop\commend-reports\node_modules\sqlite3\lib\sqlite3.js
- C:\Users\iKaros\Desktop\commend-reports\node_modules\sqlite\main.js
- C:\Users\iKaros\Desktop\commend-reports\databasemanager.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\iKaros\Desktop\commend-reports\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\iKaros\\Desktop\\commend-reports\\node_modules\\sqlite3\\lib\\sqlite3.js',
    'C:\\Users\\iKaros\\Desktop\\commend-reports\\node_modules\\sqlite\\main.js',
    'C:\\Users\\iKaros\\Desktop\\commend-reports\\databasemanager.js'
  ]
}

**Comment by BeepIsla** [comment]
Delete your node_modules folder and do `npm install` again
