### ISSUE TITLE
COMMEND TIME OUT WHEN YOU TRY +20 COMMENDS

### ISSUE THREAD

**Issue by iKaros90** [BeepIsla/csgo-commend-bot#405]
**Detailed bug description**
When i tried set for example, 60 commends in differents IP's (with friends...) and different Dev API i can get only 20 commends every 5 minut +-.

**Error**
```
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 233 operational accounts
 Parsing target account...
 Chunking 20 accounts into groups of 20...
 Logging in on chunk 1/1
 [elsiealbanese2005] Logging into Steam
 [emilylu90] Logging into Steam
 [emmanewman59] Logging into Steam
 [eric2000carey] Logging into Steam
 [ernestkoopman48] Logging into Steam
 [essie1980frank] Logging into Steam
 [essietempesti1996] Logging into Steam
 [ethan2012vidal] Logging into Steam
 [ethelsano66] Logging into Steam
 [eugeniabettini2004] Logging into Steam
 [eulaporter2000] Logging into Steam
 [euniceanderson43] Logging into Steam
 [frankcarraresi1988] Logging into Steam
 [gabrielschneider2017] Logging into Steam
 [garretthidalgo2003] Logging into Steam
 [gary10kurt] Logging into Steam
 [genehicks2002] Logging into Steam
 [geneorlandini1991] Logging into Steam
 [georgiasusini1997] Logging into Steam
 [gertrudefleming71] Logging into Steam
 [emilylu90] Logged onto Steam - GC Time: 2020-5-5 16:51:46
 [emilylu90] Authenticated to anonymous server with ticket 1636662139
 [ernestkoopman48] Logged onto Steam - GC Time: 2020-5-5 16:51:51
 [emmanewman59] Logged onto Steam - GC Time: 2020-5-5 16:51:51
 [elsiealbanese2005] Logged onto Steam - GC Time: 2020-5-5 16:51:51
 [ethan2012vidal] Logged onto Steam - GC Time: 2020-5-5 16:51:51
 [eulaporter2000] Logged onto Steam - GC Time: 2020-5-5 16:51:51
 [essietempesti1996] Logged onto Steam - GC Time: 2020-5-5 16:51:52
 [euniceanderson43] Logged onto Steam - GC Time: 2020-5-5 16:51:52
 [essie1980frank] Logged onto Steam - GC Time: 2020-5-5 16:51:52
 [eugeniabettini2004] Logged onto Steam - GC Time: 2020-5-5 16:51:52
 [elsiealbanese2005] Authenticated to anonymous server with ticket 3504712781
 [ernestkoopman48] Authenticated to anonymous server with ticket 3408108313
 [ethan2012vidal] Authenticated to anonymous server with ticket 130517587
 [eulaporter2000] Authenticated to anonymous server with ticket 3338843779
 [essie1980frank] Authenticated to anonymous server with ticket 976720233
 [emmanewman59] Authenticated to anonymous server with ticket 4136885765
 [euniceanderson43] Authenticated to anonymous server with ticket 1163952309
 [eugeniabettini2004] Authenticated to anonymous server with ticket 1868589328
 [essietempesti1996] Authenticated to anonymous server with ticket 1447725642
 [emilylu90] Failed to commend (1/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [elsiealbanese2005] Failed to commend (2/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [ernestkoopman48] Failed to commend (3/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [ethan2012vidal] Failed to commend (4/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [eulaporter2000] Failed to commend (5/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [essie1980frank] Failed to commend (6/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [emmanewman59] Failed to commend (7/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [euniceanderson43] Failed to commend (8/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [eugeniabettini2004] Failed to commend (9/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [essietempesti1996] Failed to commend (10/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\iKaros\\Desktop\\Steam\\commend-reports\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
```

**Config**
```
{
	"commend": {
		"friendly": 20,
		"teaching": 20,
		"leader": 20
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "LINK OF ACC",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "APIID",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v12.16.3` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
1. You have proxies disabled in your config

2. Its possible Valve changed things a while ago making it 20 commends per-account, instead of per-IP. Nothing I can do.

**Comment by iKaros90** [comment]
I am not using proxies, just friends using your software with different accounts / ips.

**Comment by BeepIsla** [comment]
I suppose this is enough proof that Valve made changes recently. Seems like they are now limiting commends based on account and not IP. As I said, nothing I can do.

**Comment by iKaros90** [comment]
All
