### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by simplehard** [BeepIsla/csgo-commend-bot#431]
TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined
    at SteamUser.loggedOn (C:\Users\Matheus Henriques\Desktop\Bot De Elogios 2020\helpers\account.js:113:50)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) Promise {
  <rejected> TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined
      at SteamUser.loggedOn (C:\Users\Matheus Henriques\Desktop\Bot De Elogios 2020\helpers\account.js:113:50)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

config: {
	"commend": {
		"friendly": 10,
		"teaching": 10,
		"leader": 10
	},
	"account": {
		"username": "mathsye123",
		"password": "xxxxx",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "https://steamcommunity.com/id/simplehardbtw",
	"perChunk": 10,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "2B***********FC",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
Delete protobufs folder
