### ISSUE TITLE
Commend errors

### ISSUE THREAD

**Issue by OliverMV** [BeepIsla/csgo-commend-bot#433]
**Detailed bug description**
Commend errors, it just say timeout with all the 2500 accounts i have

**Error**
```
 [0bkpL7Ma] Failed to commend (4/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\olive\\OneDrive\\Skrivebord\\csgo-commend-bot-master2\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
```

**Config**
```
{
	"commend": {
		"friendly": 5,
		"teaching": 5,
		"leader": 5
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/olilucky69/",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxxxx",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: v12.16.3

**Comment by NeresFPS** [comment]
#428  ?

**Comment by puuska** [comment]
See issue #428, commend bots are patched as for now. You need to either wait for fix or go for paid options like Sinlxye

**Comment by Waxenn** [comment]
@puuska 
We don't want to make money

**Comment by AmaranthLoren** [comment]
LOGIN method still works great, SERVER method is fixed. perChunk - 2, cooldown - 5000

**Comment by BeepIsla** [comment]
Duplicate as mentioned above
