### ISSUE TITLE
Failed to send message: Timeout

### ISSUE THREAD

**Issue by MrDioogo** [BeepIsla/csgo-commend-bot#434]
**Detailed bug description**
Failed to send message: Timeout

**Error**
```
C:\Users\pcmultimedia\Desktop\MrDioogo\SteamBots\CommendBot>node index.js
 Checking for new update... 
 Up to date! 
 Checking protobufs... 
 Found protobufs 
 Opening database... 
 There are a total of 3 operational accounts 
 Parsing target account... 
 Chunking 1 account into groups of 20...
 Logging in on chunk 1/1
 [ungenesscrabi4lepri40] Logging into Steam
 [ungenesscrabi4lepri40] Logged onto Steam - GC Time: 16/05/2020, 21:17:35
 [ungenesscrabi4lepri40] Authenticated to anonymous server with ticket 4288835269
 [ungenesscrabi4lepri40] Failed to commend (1/1) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\pcmultimedia\\Desktop\\MrDioogo\\SteamBots\\CommendBot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 Chunk 1/1 finished with 0 successful commends and 1 failed commend
 Finished all chunks with a total of 0 successful and 1 failed commend
```

**Config**
```
{
	"commend": {
		"friendly": 1,
		"teaching": 1,
		"leader": 1
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/mrdioogo",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v13.2.0` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by trustyuy** [comment]
same

**Comment by Craxto** [comment]
https://github.com/BeepIsla/csgo-commend-bot/issues/428 
Maybe take a look at the existing issues before you make a new thread.

**Comment by alioan** [comment]
@Craxto indeed :)

**Comment by BeepIsla** [comment]
Duplicate
