### ISSUE TITLE
Failed to commend-Timeout

### ISSUE THREAD

**Issue by Th1212** [BeepIsla/csgo-commend-bot#448]
**Detailed bug description**
Failed to commend-timeout

**Error**
```
 [Accountname] Failed to commend (19/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (D:\\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
```

**Config**
```
{
	"commend": {
		"friendly": 60,
		"teaching": 60,
		"leader": 60
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "set",
		"password": "set",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "---",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: v12.16.1
- Script version: 2.6.1

**Additional information**
If I use this on my main accounts, it often works. But now I want to commend a friend's account and only 1-3 accounts per chunk are working, the others fail to commend and show a timeout then. Is there a problem with the server maybe? Because I used a different than he uses right now.

**Comment by BeepIsla** [comment]
#428
