### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OfficialMelon** [BeepIsla/csgo-commend-bot#461]
**Detailed bug description**
I start index.js and this is bugging

**Error**
```
C:\Users\Данил\Documents\GitHub\csgo-commend-bot>node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 2 operational accounts
 Parsing target account...
 Chunking 2 accounts into groups of 20...
 Logging in on chunk 1/1
 [nakrutka_ot_melona_1] Logging into Steam
 [nakrutka_ot_melona_2] Logging into Steam
 [nakrutka_ot_melona_1] Logged onto Steam - GC Time: 2020-6-17 15:45:29
(node:5784) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'k_EMsgClientAuthList' of undefined
    at C:\Users\Данил\Documents\GitHub\csgo-commend-bot\helpers\account.js:257:37
(node:5784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 [nakrutka_ot_melona_2] Logged onto Steam - GC Time: 2020-6-17 15:45:29
(node:5784) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'k_EMsgClientAuthList' of undefined
    at C:\Users\Данил\Documents\GitHub\csgo-commend-bot\helpers\account.js:257:37
(node:5784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Config**
```
{
	"commend": {
		"friendly": 2,
		"teaching": 2,
		"leader": 2
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/itzmelon",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "****",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: `v12.18.0` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Delete protobufs folder

**Comment by OfficialMelon** [comment]
1 more error
![image](https://user-images.githubusercontent.com/47828778/84927971-eda4b480-b0cd-11ea-94db-3b1926d32944.png)

**Comment by BeepIsla** [comment]
Something is blocking Github access which is required to download the protobufs. Find what the problem is and fix it, I can't help with that.

Alternatively download [this](https://github.com/SteamDatabase/Protobufs/archive/master.zip) and extract it into your commend bot directory, then rename it to `protobufs`. In the end the folder should look something like this:

- `index.js`
- `config.json`
- `protobufs`
  - `steam`
    - `*.proto` (A lot of `proto` files)
  - `csgo`
    - `*.proto` (A lot of `proto` files)

**Comment by OfficialMelon** [comment]
i haven't access

**Comment by BeepIsla** [comment]
As I said: Something is blocking access to the download on your PC/Router. I don't know why and I cannot help you with this. You have to find the problem yourself and fix it or find a different way of downloading the linked ZIP file.

**Comment by OfficialMelon** [comment]
why i am times out?

**Comment by OfficialMelon** [comment]
in the account settings, I disabled Steam Guard, authorization is successful, but I still writes Timed outut

**Comment by OfficialMelon** [comment]
![image](https://user-images.githubusercontent.com/47828778/84940111-a7f0e780-b0df-11ea-8522-05f4d34a14f4.png)

**Comment by BeepIsla** [comment]
Your issue is now the same as this: #428 read it for more information, there is a lot.
