### ISSUE TITLE
Error: InvalidPassword

### ISSUE THREAD

**Issue by Seteziin** [BeepIsla/csgo-commend-bot#462]
**Detailed question description**
![image](https://user-images.githubusercontent.com/67118259/85054245-24340b00-b172-11ea-8f85-746df4421f93.png)

 Logging into fetcher account...
Error: InvalidPassword
    at SteamUser.<anonymous> (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\logon.js:458:16)
    at C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\messages.js:543:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\messages.js:478:7)
    at SteamUser.processMulti (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\messages.js:570:9)
    at SteamUser.<anonymous> (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\messages.js:564:16)
    at C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\messages.js:543:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\messages.js:478:7)
    at TCPConnection._readMessage (C:\Users\Riick\Desktop\Pastas\elogios 2.6.1\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\node_modules\steam-user\components\connection_protocols\tcp.js:193:12) {
  eresult: 5

**Config**
```
{
	"commend": {
		"friendly": 100,
		"teaching": 100,
		"leader": 100
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/*******",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "*******",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v12.16.3`
- Script version: `2.6.1`

**Comment by BeepIsla** [comment]
Did you try reading the actual error? Your fetcher account is invalid. You need to enter an actual account in there.

**Comment by CristianAdv** [comment]
"type": "COMMEND",
	"method": "SERVER",

and is asking for login account id and password
