### ISSUE TITLE
Commends Successful, Yet No Commends

### ISSUE THREAD

**Issue by hyppr** [BeepIsla/csgo-commend-bot#473]
**Detailed bug description**
The commend bot works as normal, except I am not receiving any of the commends. I left the bot on overnight, and I saw the first chunk was 8 successful, except when I logged on this morning I had only gone up by 1 commend.

**Config**
```
https://gyazo.com/aff12d2fa26a018b3f00fb1881c289dc
```

**Version**
- NodeJS: `v12.9.1`
- Script version: `2.8.2`

**Comment by BeepIsla** [comment]
This is an old unknown problem which nobody seems to have a solution for, it either happens or doesn't happen. You can try backing up your database and then wiping it to try again with all accounts.

**Comment by hyppr** [comment]
> This is an old unknown problem which nobody seems to have a solution for, it either happens or doesn't happen. You can try backing up your database and then wiping it to try again with all accounts.
> 
> 

Ill try to wipe the database from databasemanager.js and add the accounts again

**Comment by vqr1337** [comment]
The commendbot tries to commend u twice, with one account. You can only get one commend for one account. so 1000 accounts = MAX 1000 commends.

**Comment by hyppr** [comment]
> The commendbot tries to commend u twice, with one account. You can only get one commend for one account. so 1000 accounts = MAX 1000 commends.

i dont understand what you mean? ive got 19k accounts, im doing the same method as before that i used to get 2000 commends

**Comment by MAGIKPLAYGAMES** [comment]
I have some problem with this bot :/ https://i.imgur.com/P6QuDCU.png

**Comment by BeepIsla** [comment]
> I have some problem with this bot :/ https://i.imgur.com/P6QuDCU.png

Your issue is entirely unrelated, do not hijack issue thread unrelated to your problem. Your problem is already answered [here](https://github.com/BeepIsla/csgo-commend-bot/issues/469#issuecomment-650219405).

**Comment by kezyon210** [comment]
have this error: 

TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined
    at SteamUser.loggedOn (C:\Users\Nicolas\Desktop\csgo-commend-bot-master\helpers\account.js:114:50)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) Promise {
  <rejected> TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined
      at SteamUser.loggedOn (C:\Users\Nicolas\Desktop\csgo-commend-bot-master\helpers\account.js:114:50)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
}

**Comment by BeepIsla** [comment]
> have this error:
> 
> TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined
> at SteamUser.loggedOn (C:\Users\Nicolas\Desktop\csgo-commend-bot-master\helpers\account.js:114:50)
> at processTicksAndRejections (internal/process/task_queues.js:85:5) Promise {
> TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined
> at SteamUser.loggedOn (C:\Users\Nicolas\Desktop\csgo-commend-bot-master\helpers\account.js:114:50)
> at processTicksAndRejections (internal/process/task_queues.js:85:5)
> }

You too, do not hijack issue thread. Make your own. Your solution is to delete the protobufs folder and restart.

**Comment by timlzh** [comment]
@hyppr dude,ive met the same problem ,but i fixed it by enlarge cooldown time.You can try it.
Whats more,i want to know where has 19k that much accounts come from.I dont have enough account.I want more accounts too

**Comment by Jaeger33211Sec** [comment]
> **Detailed bug description**
> The commend bot works as normal, except I am not receiving any of the commends. I left the bot on overnight, and I saw the first chunk was 8 successful, except when I logged on this morning I had only gone up by 1 commend.
> 
> **Config**
> 
> ```
> https://gyazo.com/aff12d2fa26a018b3f00fb1881c289dc
> ```
> 
> **Version**
> 
> * NodeJS: `v12.9.1`
> * Script version: `2.8.2`

Probably a account issue.
From 160k accs 2k are commending but the target is not getting them.

**Comment by ricardosxx** [comment]
me too The commend bot works as normal, except I am not receiving any of the commends.

**Comment by alioan** [comment]
If u have wiped your database, until all the info is gatjered again, the program will try to commend u using accounts which have commended u before as well

**Comment by ricardosxx** [comment]
> If u have wiped your database, until all the info is gatjered again, the program will try to commend u using accounts which have commended u before as well

I don't know if an account I've used before is valid for multiple compliments

**Comment by inbroso** [comment]
Tested it with 1k accounts/commends as well and all commends which were successful also have been added to my account.
Are you sure you haven't commended the account with these botaccounts already? You can only commend an account once with one botaccount. So with 1k accounts you can maximum give an account 1k commends and not more.




(Btw thats why I wanted the feature for deleting accounts without the commend history, if you reset the database and then add the accounts again, it just starts to commend with all accounts again because it didn't know it commended the account again)

**Comment by inbroso** [comment]
> > The commendbot tries to commend u twice, with one account. You can only get one commend for one account. so 1000 accounts = MAX 1000 commends.
> 
> i dont understand what you mean? ive got 19k accounts, im doing the same method as before that i used to get 2000 commends

You are probably trying to commend the account with the same 2000 accounts which commended already, common mistake which I already did by mistake.

**Comment by hyppr** [comment]
> > > The commendbot tries to commend u twice, with one account. You can only get one commend for one account. so 1000 accounts = MAX 1000 commends.
> > 
> > 
> > i dont understand what you mean? ive got 19k accounts, im doing the same method as before that i used to get 2000 commends
> 
> You are probably trying to commend the account with the same 2000 accounts which commended already, common mistake which I already did by mistake.

I sorted my accounts alphabetically and deleted a thousand just in case, same thing happens, commends are saying successful yet I dont receive any.

**Comment by hyppr** [comment]
> me too The commend bot works as normal, except I am not receiving any of the commends.

did you find a way to fix it?

**Comment by inbroso** [comment]
> > > > The commendbot tries to commend u twice, with one account. You can only get one commend for one account. so 1000 accounts = MAX 1000 commends.
> > > 
> > > 
> > > i dont understand what you mean? ive got 19k accounts, im doing the same method as before that i used to get 2000 commends
> > 
> > 
> > You are probably trying to commend the account with the same 2000 accounts which commended already, common mistake which I already did by mistake.
> 
> I sorted my accounts alphabetically and deleted a thousand just in case, same thing happens, commends are saying successful yet I dont receive any.

I tested it with about 6000-7000 accounts which I already used to commend a second account and nearly all commends were received on my account.
Be advised that you dont delete the commend history in your database, otherwise the bot will commend with all accounts which already have been used to bot and then the commends arent received because you already got them on your account

**Comment by hyppr** [comment]
> > > > > The commendbot tries to commend u twice, with one account. You can only get one commend for one account. so 1000 accounts = MAX 1000 commends.
> > > > 
> > > > 
> > > > i dont understand what you mean? ive got 19k accounts, im doing the same method as before that i used to get 2000 commends
> > > 
> > > 
> > > You are probably trying to commend the account with the same 2000 accounts which commended already, common mistake which I already did by mistake.
> > 
> > 
> > I sorted my accounts alphabetically and deleted a thousand just in case, same thing happens, commends are saying successful yet I dont receive any.
> 
> I tested it with about 6000-7000 accounts which I already used to commend a second account and nearly all commends were received on my account.
> Be advised that you dont delete the commend history in your database, otherwise the bot will commend with all accounts which already have been used to bot and then the commends arent received because you already got them on your account

yeah i tried and it didnt work, still same thing

**Comment by hyppr** [comment]
update: tried to get a friend to commend me, didnt go up. commended someone else in our game, theirs went up. so its something to do with my account. i guess im commend banned or something

**Comment by BeepIsla** [comment]
Only thing that makes sense is your accounts already commended you. There is no other possible reason.

**Comment by 2kFlow** [comment]
> update: tried to get a friend to commend me, didnt go up. commended someone else in our game, theirs went up. so its something to do with my account. i guess im commend banned or something

any fixes yet?

**Comment by 2kFlow** [comment]
Guys !!! I got a fix , atleast worked for me . I added only 20 steam accounts in the accounts.txt file and added the value "20" in the commends section in the config . It worked for me and I did it 8 different times and it worked . So , add 20 accounts to the text file and 20 commend in the config and try . You can do this multiple times
