### ISSUE TITLE
need help with this error

### ISSUE THREAD

**Issue by fiskerface** [BeepIsla/csgo-commend-bot#493]
C:\Users\xyz\Desktop\repbot>index
internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for 'C:\Users\xyz\Desktop\repbot\node_modules\sqlite'
[90m    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)[39m
[90m    at applyExports (internal/modules/cjs/loader.js:499:14)[39m
[90m    at resolveExports (internal/modules/cjs/loader.js:548:12)[39m
[90m    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)[39m
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:859:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1028:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\xyz\Desktop\repbot\index.js:1:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:1139:30)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m
}

can someone help me? I updated like allways because I did not used this bot for like 3month

now I have this problem

**Comment by BeepIsla** [comment]
What NodeJS version are you using? `node -v`

**Comment by fiskerface** [comment]
C:\Users\xyz\Desktop\repbot>node -v
v13.5.0

**Comment by BeepIsla** [comment]
Yes, download [v12 LTS](https://nodejs.org/)
