### ISSUE TITLE
Account Login?

### ISSUE THREAD

**Issue by DennisMariquit** [BeepIsla/csgo-commend-bot#503]
"Error: GC connection timeout - Hello
    at SteamUser.loggedOn (E:\Csgo\csgo-commend-bot-master\helpers\account.js:129:14) Promise {
  <rejected> Error: GC connection timeout - Hello
      at SteamUser.loggedOn (E:\Csgo\csgo-commend-bot-master\helpers\account.js:129:14)"

Latest Version

**Comment by BeepIsla** [comment]
Config?

**Comment by DennisMariquit** [comment]
https://pastebin.com/cCyGPLXV

**Comment by DennisMariquit** [comment]
Sorry I'm just dumb XD I fixed it XD
