### ISSUE TITLE
node DatabaseManager.js Error

### ISSUE THREAD

**Issue by layihvh** [BeepIsla/csgo-commend-bot#533]
internal/modules/cjs/loader.js:621
  throw e;
  ^

Error: No valid exports main found for 'C:\Users\user\Desktop\Commend\csgo-commend-bot-master\node_modules\sqlite'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\user\Desktop\Commend\csgo-commend-bot-master\databaseManager.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1128:30) {
  code: 'MODULE_NOT_FOUND'
}

can someone help me?

**Comment by BeepIsla** [comment]
Use the issue template.

NodeJS version?

**Comment by layihvh** [comment]
I tried installed 12.18.2 and now its working.
