### ISSUE TITLE
Commend bot error

### ISSUE THREAD

**Issue by andrei1002** [BeepIsla/csgo-commend-bot#540]
Error: InvalidPassword
    at SteamUser.<anonymous> (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:494:16)
    at C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
    at SteamUser.processMulti (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:582:9)
    at SteamUser.<anonymous> (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:576:16)
    at C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
    at TCPConnection._readMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:193:12) {
  eresult: 5
} Promise {
  <rejected> Error: InvalidPassword
      at SteamUser.<anonymous> (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:494:16)
      at C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
      at Array.forEach (<anonymous>)
      at HandlerManager.emit (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
      at SteamUser._handleMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
      at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
      at SteamUser._handleNetMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
      at SteamUser.processMulti (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:582:9)
      at SteamUser.<anonymous> (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:576:16)
      at C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
      at Array.forEach (<anonymous>)
      at HandlerManager.emit (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
      at SteamUser._handleMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
      at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
      at SteamUser._handleNetMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
      at TCPConnection._readMessage (C:\Users\Andrei\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:193:12) {
    eresult: 5
  }
},
This error apear when i run node index.js

**Comment by BeepIsla** [comment]
Config?

**Comment by andrei1002** [comment]
{
	"commend": {
		"friendly": 1,
		"teaching": 1,
		"leader": 1
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561198346837528/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "hidden",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
Read the README. You are trying to use the `fetcher` without providing an account. So either put in a bot account in the `fetcher` section of your config or stop trying to use `AUTO`.
