### ISSUE TITLE
Error: GC connection timeout - Hello

### ISSUE THREAD

**Issue by ffff232** [BeepIsla/csgo-commend-bot#546]
Error: GC connection timeout - Hello
    at SteamUser.loggedOn (C:\aadas\helpers\account.js:140:14) Promise {
  <rejected> Error: GC connection timeout - Hello
      at SteamUser.loggedOn (C:\aadas\helpers\account.js:140:14)

**Comment by BeepIsla** [comment]
Config?

**Comment by RoyalBaron** [comment]
same error, worked fine 3 days ago but now it gives that error quite often

**Comment by hellokvn** [comment]
Same. Worked today and yesterday, even every reported player had a few timeouts, but now it's like a 100% timeout rate. The config is fine. The code is untouched.

```json
{
  "commend": {
    "friendly": 5,
    "teaching": 10,
    "leader": 15
  },
  "report": {
    "aimbot": 10,
    "wallhack": 10,
    "speedhack": 10,
    "teamharm": 10,
    "abusive": 10
  },
  "account": {
    "username": "",
    "password": "",
    "sharedSecret": ""
  },
  "fetcher": {
    "username": "a-working-username",
    "password": "a-working-password",
    "sharedSecret": "",
    "maxTries": 10,
    "tryDelay": 2500,
    "askSteamGuard": true
  },
  "proxy": {
    "enabled": false,
    "file": "proxies.txt",
    "switchProxyEveryXaccounts": 20
  },
  "type": "REPORT",
  "method": "SERVER",
  "target": "https://steamcommunity.com/id/a-working-profile-of-a-player-in-a-running-mm",
  "serverID": "auto",
  "matchID": "0",
  "perChunk": 20,
  "betweenChunks": 300000,
  "cooldown": 28800000,
  "showCommends": false,
  "autoReportOnMatchEnd": false,
  "switchServerAfterChunks": 5,
  "protocol": "Auto",
  "steamWebAPIKey": "A WORKING API KEY",
  "disableUpdateCheck": false
}

```

**Comment by BeepIsla** [comment]
Timeouts are **NOT** the same as GC Connection errors. You can't use this bot for Matchmaking, Valve blocks it and nobody has given me a fix for it yet though I know its possible.

**Comment by RoyalBaron** [comment]
I do them on community servers though, maybe valve hotfixed it ?

**Comment by hellokvn** [comment]
What's the meaning of GC?

**Comment by BeepIsla** [comment]
GC stands for GameCoordinator, its what Valve calls their backend for their games. Also known as "CSGO Network"
