### ISSUE TITLE
sorry  have  anther problem here 

### ISSUE THREAD

**Issue by medhat8989** [BeepIsla/csgo-commend-bot#557]
Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 2571 operational accounts
 Parsing target account...
 Chunking 30 accounts into groups of 20...
 Parsing server input
 Logging into fetcher account...
Error: Failed to log in within given 60000ms
    at Timeout._onTimeout (C:\Users\k\Desktop\csgo-commend-bot-master\csgo-commend-bot-master\helpers\account.js:54:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) Promise {
  <rejected> Error: Failed to log in within given 60000ms
      at Timeout._onTimeout (C:\Users\k\Desktop\csgo-commend-bot-master\csgo-commend-bot-master\helpers\account.js:54:12)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
}
PS C:\Users\k\Desktop\csgo-commend-bot-master\csgo-commend-bot-master>

this happen when i try to report :(  + this problem to look down 
 [Yankswin27] Failed to report (5/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\k\\Desktop\\csgo-commend-bot-master\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [Zsolesz6] Failed to report (6/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\k\\Desktop\\csgo-commend-bot-master\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [a12310222] Failed to report (7/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\k\\Desktop\\csgo-commend-bot-master\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}

**Comment by BeepIsla** [comment]
Late reply: Config?

**Comment by kriteax1337** [comment]
I have the same issue. My config: 
{
	"commend": {
		"friendly": 20,
		"teaching": 20,
		"leader": 20
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/myuid/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "myapikey",
	"disableUpdateCheck": false
}

**Comment by xxKrycha** [comment]
try to change "serverID": "auto", to "serverID": "Id your server",
