### ISSUE TITLE
Error: InvalidPassword help me out

### ISSUE THREAD

**Issue by 2kFlow** [BeepIsla/csgo-commend-bot#561]
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 6 operational accounts
 Parsing target account...
 Chunking 1 account into groups of 20...
 Parsing server input
 Logging into fetcher account...

    at SteamUser.<anonymous> (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:494:16)
    at C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
    at SteamUser.processMulti (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:582:9)
    at SteamUser.<anonymous> (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:576:16)
    at C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
    at TCPConnection._readMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:193:12) {
  eresult: 5
} Promise {
  <rejected> Error: InvalidPassword
      at SteamUser.<anonymous> (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:494:16)
      at C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
      at Array.forEach (<anonymous>)
      at HandlerManager.emit (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
      at SteamUser._handleMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
      at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
      at SteamUser._handleNetMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
      at SteamUser.processMulti (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:582:9)
      at SteamUser.<anonymous> (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:576:16)
      at C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
      at Array.forEach (<anonymous>)
      at HandlerManager.emit (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
      at SteamUser._handleMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
      at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
      at SteamUser._handleNetMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
      at TCPConnection._readMessage (C:\Users\shres\OneDrive\Pictures\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:193:12) {
    eresult: 5
  }
}

.........................................................................................................................................................................................................................................................................

When i try to commend bot , it says invalid password and im pretty sure the password is correct

**Comment by BeepIsla** [comment]
Why do you not follow the issue template? There are so much information missing here. Luckily I know what the problem is without even seeing anything because its happening so often and its mindbogglingly how everyone misses this one simple step.

Just put a bot account into the `fetcher` section of your config.

**Comment by 2kFlow** [comment]
> Why do you not follow the issue template? There are so much information missing here. Luckily I know what the problem is without even seeing anything because its happening so often and its mindbogglingly how everyone misses this one simple step.
> 
> Just put a bot account into the `fetcher` section of your config.

Wdym by i should add a bot acc into the fetcher?

**Comment by BeepIsla** [comment]
Open your config, look at the `fetcher` part, and replace `Account` & `Password` with some account. Just generate an account quickly, put it in there and forget about it.
