### ISSUE TITLE
gyp error

### ISSUE THREAD

**Issue by luissuniga** [BeepIsla/csgo-commend-bot#570]
I'm getting this when installing

> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.7.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Gaivota Do Nemo\\Desktop\\csgo-commend-bot-master\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Gaivota Do Nemo\\Desktop\\csgo-commend-bot-master\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\sqlite3
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gaivota Do Nemo\\Desktop\\csgo-commend-bot-master\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN unquirer@1.0.0 requires a peer of inquirer@^5.2.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gaivota Do Nemo\AppData\Roaming\npm-cache\_logs\2020-08-02T16_09_10_113Z-debug.log
PS C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master>

**Comment by BeepIsla** [comment]
Read the README. Why do you have NodeJS v14 when it tell you to use v12? Uninstall v14 and install v12.

**Comment by luissuniga** [comment]
OK now i'm getting this.
I've typed the right account and password like this 
"account:password" so it should work correctly

 Logging into fetcher account...
Error: InvalidPassword
    at SteamUser.<anonymous> (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:494:16)
    at C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
    at SteamUser.processMulti (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:582:9)
    at SteamUser.<anonymous> (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:576:16)
    at C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
    at TCPConnection._readMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:193:12) {
  eresult: 5
} Promise {
  <rejected> Error: InvalidPassword
      at SteamUser.<anonymous> (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:494:16)
      at C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
      at Array.forEach (<anonymous>)
      at HandlerManager.emit (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
      at SteamUser._handleMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
      at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
      at SteamUser._handleNetMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
      at SteamUser.processMulti (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:582:9)
      at SteamUser.<anonymous> (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:576:16)
      at C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
      at Array.forEach (<anonymous>)
      at HandlerManager.emit (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
      at SteamUser._handleMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
      at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
      at SteamUser._handleNetMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
      at TCPConnection._readMessage (C:\Users\Gaivota Do Nemo\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:193:12) {
    eresult: 5
  }
}

**Comment by BeepIsla** [comment]
You are trying to use a fetcher without providing one, again read the README. If you want to use `auto` anywhere you **have** to provide a fetcher account, so generate an account and put it in your config under `fetcher`.
