### ISSUE TITLE
Errors after block 12

### ISSUE THREAD

**Issue by 3ncoded** [BeepIsla/csgo-commend-bot#581]
**Detailed bug description**
When starting block 13 (happened on multiple occasions after redownloading) the program errors out as shown below.
After the error occurs the first time I'm unable to use index.js or databaseManager.js as they are deleted from the directory.
**Error**
```
A full error log or screenshot.
 Chunk 12/150 finished with 4 successful commends and 16 failed commends
 Waiting 300000ms...
 Logging in on chunk 13/150
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\The Meme Machine\Desktop\cs hacks\csgo-commend-bot-master\helpers\Bots.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
 Chunk 13/150 finished with 0 successful commends and 0 failed commends
 Waiting 300000ms...
 Logging in on chunk 14/150
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\The Meme Machine\Desktop\cs hacks\csgo-commend-bot-master\helpers\Bots.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
 Chunk 14/150 finished with 0 successful commends and 0 failed commends
 Waiting 300000ms...
 Logging in on chunk 15/150
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\The Meme Machine\Desktop\cs hacks\csgo-commend-bot-master\helpers\Bots.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
 Chunk 15/150 finished with 0 successful commends and 0 failed commends
 Waiting 300000ms...
 Getting an available server after 5 chunks
 Failed to fetch new server, continuing with old server 90137722461154310
 Logging in on chunk 16/150
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\The Meme Machine\Desktop\cs hacks\csgo-commend-bot-master\helpers\Bots.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
 Chunk 16/150 finished with 0 successful commends and 0 failed commends
 Waiting 300000ms...
 Logging in on chunk 17/150
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\The Meme Machine\Desktop\cs hacks\csgo-commend-bot-master\helpers\Bots.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
 Chunk 17/150 finished with 0 successful commends and 0 failed commends
 Waiting 300000ms...

The Meme Machine@The-Meme-Machine MINGW64 ~/Desktop/cs hacks/csgo-commend-bot-master
$ node index.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\The Meme Machine\Desktop\cs hacks\csgo-commend-bot-master\index.js'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)?[39m
?[90m    at internal/main/run_main_module.js:17:47?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}

The Meme Machine@The-Meme-Machine MINGW64 ~/Desktop/cs hacks/csgo-commend-bot-master
$ node databaseManager.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\The Meme Machine\Desktop\cs hacks\csgo-commend-bot-master\databaseManager.js'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)?[39m
?[90m    at internal/main/run_main_module.js:17:47?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}

```

**Config**
```
Your "config.json" - Censor your API Key and account details
{
	"commend": {
		"friendly": 3000,
		"teaching": 3000,
		"leader": 3000
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"disableUpdateCheck": false
}


```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`) v12.18.3
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`) package.json was also missing.

**Additional information**
Add any other potentially useful information about your issue here.
Not really anything special other than that accounts I am 100% sure never commended my account were being marked as already having commended it.

**Comment by 3ncoded** [comment]
![image](https://user-images.githubusercontent.com/22591877/89743370-ff3d8380-daa2-11ea-9b9f-1491c96cc556.png)
Adding how my folder looked after the error, I did not delete any files myself.

**Comment by BeepIsla** [comment]
Something is deleting the files and causing the problem. Possibly some Anti-Virus software removing them.

**Comment by 3ncoded** [comment]
Just checked and my antivirus didnt delete anything, the folder where i have it in is also excluded from my av as some programs in there were getting flagged too.

**Comment by BeepIsla** [comment]
Its definitely not something the bot does and you are the only one having this issue. I assume its somewhat time based? Such as every time you extract the files after 1 hour (12 chunks * 5 minutes delay) the files get deleted for some mysterious reason. I have absolutely no idea why this happens to you and sadly cannot help with it.

**Comment by 3ncoded** [comment]
Ah okay, thats weird, ill try to move the files to another disk and exclude the entire disk to see if that makes a difference, thanks for the help anyways!
