### ISSUE TITLE
somethings wrong in linux centos7

### ISSUE THREAD

**Issue by dreamisfuture** [BeepIsla/csgo-commend-bot#590]
# npm ci
npm WARN prepare removing existing node_modules/ before installation

> protobufjs@6.9.0 postinstall /root/csgobot/csgo-commend-bot-master/node_modules/protobufjs
> node scripts/postinstall

internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module '/root/csgobot/csgo-commend-bot-master/node_modules/protobufjs/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protobufjs@6.9.0 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protobufjs@6.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-18T01_47_50_627Z-debug.log

**Comment by BeepIsla** [comment]
Try `npm install protobufjs && npm ci`

**Comment by dreamisfuture** [comment]
# npm install protobufjs && npm ci

> protobufjs@6.10.1 postinstall /root/csgobot/csgo-commend-bo2t-master/csgo-commend-bot-master/node_modules/protobufjs
> node scripts/postinstall

internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module '/root/csgobot/csgo-commend-bo2t-master/csgo-commend-bot-master/node_modules/protobufjs/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN unquirer@1.0.0 requires a peer of inquirer@^5.2.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protobufjs@6.10.1 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protobufjs@6.10.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-19T00_38_54_705Z-debug.log

**Comment by dreamisfuture** [comment]
but when i run it in windows10 ,can work
in centos7 cant
