### ISSUE TITLE
Cannot read property split of undefined

### ISSUE THREAD

**Issue by edqx** [BeepIsla/csgo-commend-bot#605]
**Detailed bug description**
Error comes up saying that it cannot read split of undefined in the steam-user node module. The API key is correct and accounts are all supplied. Works for a few seconds before this comes up just after it tries to log into one of the accounts, then comes up with an error saying that it couldn't log in within a minute.

**Error**
```
Logging into fetcher account...
TypeError: Cannot read property 'split' of undefined
    at new TCPConnection (C:\Users\User\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:29:22)
    at SteamUser._doConnection (C:\Users\User\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:238:23)
    at C:\Users\User\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:218:8 Promise {
  <rejected> TypeError: Cannot read property 'split' of undefined
      at new TCPConnection (C:\Users\User\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:29:22)
      at SteamUser._doConnection (C:\Users\User\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:238:23)
      at C:\Users\User\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:218:8
}
Error: Failed to log in within given 60000ms
    at Timeout._onTimeout (C:\Users\User\Desktop\csgo-commend-bot-master\helpers\account.js:63:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) Promise {
  <rejected> Error: Failed to log in within given 60000ms
      at Timeout._onTimeout (C:\Users\User\Desktop\csgo-commend-bot-master\helpers\account.js:63:12)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
}
```

**Config**
```
{
	"commend": {
		"friendly": 1000,
		"teaching": 1000,
		"leader": 1000
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "~snip~",
	"serverID": "auto",
	"matchID": "auto",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "~snip~",
	"disableUpdateCheck": false
}


```

**Version**
- NodeJS: `v12.9.1` (You can find this using `node -v`)
- Script version: `2.10.0` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
I don't know. I am not looking into it anyways due to this being patched right now (#593)
