### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marki123** [BeepIsla/csgo-commend-bot#613]
i got this error where i tryed

PS C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master> node index
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 6411 operational accounts
 Parsing target account...
 Chunking 6000 accounts into groups of 20...
 Parsing server input
 Logging into fetcher account...
Error: InvalidPassword
    at SteamUser.<anonymous> (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:494:16)
    at C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
    at SteamUser.processMulti (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:582:9)
    at SteamUser.<anonymous> (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:576:16)
    at C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
    at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
    at SteamUser._handleNetMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
    at TCPConnection._readMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:193:12) {
  eresult: 5
} Promise {
  <rejected> Error: InvalidPassword
      at SteamUser.<anonymous> (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:494:16)
      at C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
      at Array.forEach (<anonymous>)
      at HandlerManager.emit (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
      at SteamUser._handleMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
      at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
      at SteamUser._handleNetMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
      at SteamUser.processMulti (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:582:9)
      at SteamUser.<anonymous> (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:576:16)
      at C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
      at Array.forEach (<anonymous>)
      at HandlerManager.emit (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
      at SteamUser._handleMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:555:24)
      at SteamUser.Coordinator.steamUser._handleMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\helpers\GameCoordinator.js:43:19)
      at SteamUser._handleNetMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:490:7)
      at TCPConnection._readMessage (C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:193:12) {
    eresult: 5
  }
}
PS C:\Users\markg\Desktop\cmdb\csgo-commend-bot-master>

**Comment by BeepIsla** [comment]
1. Read the README

2. Read the example config

3. Read the error

4. https://github.com/BeepIsla/csgo-commend-bot/issues/593
